# Generated by Django 4.1.13 on 2024-06-12 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapphome", "0005_rename_feedback_feedback_feedback_response_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
