# Generated by Django 4.1.13 on 2024-06-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapphome", "0006_delete_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_feedbacker", models.CharField(max_length=100)),
                ("email_of_feedbacker", models.EmailField(max_length=254)),
                ("Feedback_response", models.TextField()),
            ],
        ),
    ]
