# Generated by Django 4.1.13 on 2024-06-12 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapphome", "0007_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="Feedback_response",
            new_name="feedback_response",
        ),
    ]
