# Generated by Django 4.1.13 on 2024-06-14 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapphome", "0010_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="email_of_feedbacker",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="feedback",
            old_name="feedback_response",
            new_name="feedback",
        ),
        migrations.RenameField(
            model_name="feedback",
            old_name="name_of_feedbacker",
            new_name="name",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
